// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type _404DocumentDataSlicesSlice = never;

/**
 * Content for 404 documents
 */
interface _404DocumentData {
  /**
   * Slice Zone field in *404*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<_404DocumentDataSlicesSlice>; /**
   * Meta Title field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: 404.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *404*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: 404.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *404*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: 404.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * 404 document from Prismic
 *
 * - **API ID**: `404`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type _404Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<_404DocumentData>, "404", Lang>;

type ArticleDocumentDataSlicesSlice = never;

/**
 * Content for Article documents
 */
interface ArticleDocumentData {
  /**
   * Category field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.category
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  category: ContentRelationshipFieldWithData<
    [{ id: "category"; fields: ["name"] }]
  >;

  /**
   * Author field in *Article*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: article.author
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  author: ContentRelationshipFieldWithData<
    [{ id: "author"; fields: ["img", "name"] }]
  >;

  /**
   * Read time field in *Article*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 5 (min)
   * - **API ID Path**: article.read_time
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  read_time: prismic.NumberField;

  /**
   * Read time - Text field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Min
   * - **API ID Path**: article.read_time_txt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  read_time_txt: prismic.KeyTextField;

  /**
   * Date field in *Article*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: article.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Title field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Article*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: article.desc
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  desc: prismic.RichTextField;

  /**
   * Slice Zone field in *Article*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: article.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ArticleDocumentDataSlicesSlice>; /**
   * Meta Title field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: article.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Article*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: article.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Article*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: article.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Article document from Prismic
 *
 * - **API ID**: `article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArticleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ArticleDocumentData>,
    "article",
    Lang
  >;

/**
 * Content for Author documents
 */
interface AuthorDocumentData {
  /**
   * Image field in *Author*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: author.img
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Name field in *Author*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: author.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Author document from Prismic
 *
 * - **API ID**: `author`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AuthorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<AuthorDocumentData>, "author", Lang>;

/**
 * Content for Category documents
 */
interface CategoryDocumentData {
  /**
   * Name field in *Category*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: category.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;
}

/**
 * Category document from Prismic
 *
 * - **API ID**: `category`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CategoryDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CategoryDocumentData>,
    "category",
    Lang
  >;

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
  /**
   * Image field in *Contact*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Position field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.position
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  position: prismic.KeyTextField;

  /**
   * Email field in *Contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Calendar field in *Contact*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.calendar
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  calendar: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
  /**
   * Text field in *Footer*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.txt
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  txt: prismic.KeyTextField;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HeaderDocumentDataSlicesSlice = NavigationLinksSlice;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
  /**
   * CTAs field in *Header*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: header.ctas
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ctas: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary" | "Link"
    >
  >;

  /**
   * Slice Zone field in *Header*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: header.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HeaderDocumentDataSlicesSlice>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HeaderDocumentData>,
    "header",
    Lang
  >;

type HomeDocumentDataSlicesSlice = HeroHomeSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

type LandingDocumentDataSlicesSlice =
  | FeaturedArticlesSlice
  | MediaFeatureSlice
  | ContentSlice
  | HeroLandingSlice
  | TestimonialsSlice
  | FaqSlice
  | CarouselSlice
  | CtaSlice;

/**
 * Content for Landing documents
 */
interface LandingDocumentData {
  /**
   * Slice Zone field in *Landing*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LandingDocumentDataSlicesSlice>; /**
   * Meta Title field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: landing.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Landing*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: landing.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>; /**
   * Logo field in *Landing*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.logo
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Links field in *Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.lnks
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  lnks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;

  /**
   * CTA field in *Landing*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.cta
   * - **Tab**: Header
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >; /**
   * Primary color field in *Landing*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.primary_color
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  primary_color: prismic.ColorField;

  /**
   * Secondary color field in *Landing*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: landing.secondary_color
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/color
   */
  secondary_color: prismic.ColorField;

  /**
   * Font - Heading field in *Landing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Proxima Bold
   * - **API ID Path**: landing.font_heading
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  font_heading: prismic.SelectField<"Proxima Bold" | "Arial Bold", "filled">;

  /**
   * Font - Text field in *Landing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Inter
   * - **API ID Path**: landing.font_txt
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  font_txt: prismic.SelectField<"Inter" | "Helvetica", "filled">;

  /**
   * Button style field in *Landing*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Square
   * - **API ID Path**: landing.button_style
   * - **Tab**: Design
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  button_style: prismic.SelectField<
    "Square" | "Medium rounded" | "Rounded",
    "filled"
  >;
}

/**
 * Landing document from Prismic
 *
 * - **API ID**: `landing`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LandingDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<LandingDocumentData>,
    "landing",
    Lang
  >;

type RecapDocumentDataSlicesSlice = never;

/**
 * Item in *Recap → Key problem*
 */
export interface RecapDocumentDataKeyProblemItem {
  /**
   * Icon field in *Recap → Key problem*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: thunder
   * - **API ID Path**: recap.key_problem[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "thunder" | "test" | "brand" | "smile" | "checkedCalendar" | "control",
    "filled"
  >;

  /**
   * Title field in *Recap → Key problem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.key_problem[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Recap → Key problem*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.key_problem[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Recap → Opportunity*
 */
export interface RecapDocumentDataOpportunityItem {
  /**
   * Icon field in *Recap → Opportunity*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: zoom
   * - **API ID Path**: recap.opportunity[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<"zoom" | "reuse" | "hammer", "filled">;

  /**
   * Title field in *Recap → Opportunity*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.opportunity[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Recap → Opportunity*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.opportunity[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Item in *Recap → Generated Page*
 */
export interface RecapDocumentDataGeneratedPageItem {
  /**
   * Company field in *Recap → Generated Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.generated_page[].company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company: prismic.KeyTextField;

  /**
   * Role field in *Recap → Generated Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.generated_page[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * Personalization Instructions field in *Recap → Generated Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.generated_page[].personalization_instructions
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  personalization_instructions: prismic.KeyTextField;

  /**
   * Page Link field in *Recap → Generated Page*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.generated_page[].page_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  page_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *Recap → Step*
 */
export interface RecapDocumentDataStepItem {
  /**
   * Icon field in *Recap → Step*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: thunder
   * - **API ID Path**: recap.step[].icon
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  icon: prismic.SelectField<
    "thunder" | "test" | "brand" | "smile" | "checkedCalendar" | "control",
    "filled"
  >;

  /**
   * Title field in *Recap → Step*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.step[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Recap → Step*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.step[].text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  text: prismic.RichTextField;
}

/**
 * Content for Recap documents
 */
interface RecapDocumentData {
  /**
   * Title field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Slice Zone field in *Recap*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<RecapDocumentDataSlicesSlice>; /**
   * Client Logo field in *Recap*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.client_logo
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  client_logo: prismic.ImageField<never>;

  /**
   * Eyebrow field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.hero_eyebrow
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  hero_eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.hero_title
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_title: prismic.RichTextField;

  /**
   * Text field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.hero_text
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  hero_text: prismic.RichTextField;

  /**
   * Contact field in *Recap*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.contact
   * - **Tab**: Hero
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  contact: ContentRelationshipFieldWithData<
    [
      {
        id: "contact";
        fields: ["image", "name", "position", "email", "calendar"];
      },
    ]
  >; /**
   * Eyebrow field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.understanding_eyebrow
   * - **Tab**: Understanding
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  understanding_eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.understanding_title
   * - **Tab**: Understanding
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  understanding_title: prismic.RichTextField;

  /**
   * Text field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.understanding_text
   * - **Tab**: Understanding
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  understanding_text: prismic.RichTextField;

  /**
   * Key problem field in *Recap*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.key_problem[]
   * - **Tab**: Understanding
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  key_problem: prismic.GroupField<
    Simplify<RecapDocumentDataKeyProblemItem>
  >; /**
   * Title field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.opportunities_title
   * - **Tab**: Opportunities
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  opportunities_title: prismic.RichTextField;

  /**
   * Opportunity field in *Recap*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.opportunity[]
   * - **Tab**: Opportunities
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  opportunity: prismic.GroupField<
    Simplify<RecapDocumentDataOpportunityItem>
  >; /**
   * Title field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.data_title
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  data_title: prismic.RichTextField;

  /**
   * Text field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.data_text
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  data_text: prismic.RichTextField;

  /**
   * Generated Page field in *Recap*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.generated_page[]
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  generated_page: prismic.GroupField<
    Simplify<RecapDocumentDataGeneratedPageItem>
  >; /**
   * Eyebrow field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.next_eyebrow
   * - **Tab**: Next Steps
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  next_eyebrow: prismic.KeyTextField;

  /**
   * Title field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.next_title
   * - **Tab**: Next Steps
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  next_title: prismic.RichTextField;

  /**
   * Text field in *Recap*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.next_text
   * - **Tab**: Next Steps
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  next_text: prismic.RichTextField;

  /**
   * Step field in *Recap*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.step[]
   * - **Tab**: Next Steps
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  step: prismic.GroupField<Simplify<RecapDocumentDataStepItem>>;

  /**
   * Buttons field in *Recap*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.buttons
   * - **Tab**: Next Steps
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Filled" | "Outlined"
    >
  >; /**
   * Meta Title field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: recap.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Recap*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: recap.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Recap*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: recap.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Recap document from Prismic
 *
 * - **API ID**: `recap`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type RecapDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<RecapDocumentData>, "recap", Lang>;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Company name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_name
   * - **Tab**: Company
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  company_name: prismic.KeyTextField;

  /**
   * Company logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.company_logo
   * - **Tab**: Company
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  company_logo: prismic.ImageField<never>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | _404Document
  | ArticleDocument
  | AuthorDocument
  | CategoryDocument
  | ContactDocument
  | FooterDocument
  | HeaderDocument
  | HomeDocument
  | LandingDocument
  | RecapDocument
  | SettingsDocument;

/**
 * Item in *Carousel → Default → Primary → Grp*
 */
export interface CarouselSliceDefaultPrimaryGrpItem {
  /**
   * Article field in *Carousel → Default → Primary → Grp*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.grp[].article
   * - **Documentation**: https://prismic.io/docs/fields/content-relationship
   */
  article: ContentRelationshipFieldWithData<
    [
      {
        id: "article";
        fields: [
          "read_time",
          "date",
          "img",
          "title",
          "desc",
          {
            id: "author";
            customtypes: [{ id: "author"; fields: ["img", "name"] }];
          },
          {
            id: "category";
            customtypes: [{ id: "category"; fields: ["name"] }];
          },
          "read_time_txt",
        ];
      },
    ]
  >;
}

/**
 * Item in *Carousel → Variation 1 → Primary → Grp*
 */
export interface CarouselSliceVariation1PrimaryGrpItem {
  /**
   * Image field in *Carousel → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation1.primary.grp[].img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Item in *Carousel → Variation 2 → Primary → Grp*
 */
export interface CarouselSliceVariation2PrimaryGrpItem {
  /**
   * Logo field in *Carousel → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation2.primary.grp[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Carousel → Default → Primary*
 */
export interface CarouselSliceDefaultPrimary {
  /**
   * Ontitle field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Blog
   * - **API ID Path**: carousel.default.primary.ontitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ontitle: prismic.RichTextField;

  /**
   * Title field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Button - Text field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View all
   * - **API ID Path**: carousel.default.primary.btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;

  /**
   * Grp field in *Carousel → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<CarouselSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Carousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CarouselSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Carousel → Variation 1 → Primary*
 */
export interface CarouselSliceVariation1Primary {
  /**
   * Title field in *Carousel → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Carousel → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Carousel → Variation 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation1.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<CarouselSliceVariation1PrimaryGrpItem>>;
}

/**
 * Variation 1 variation for Carousel Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<CarouselSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Carousel → Variation 2 → Primary*
 */
export interface CarouselSliceVariation2Primary {
  /**
   * Title field in *Carousel → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Grp field in *Carousel → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: carousel.variation2.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<CarouselSliceVariation2PrimaryGrpItem>>;
}

/**
 * Variation 2 variation for Carousel Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<CarouselSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Carousel*
 */
type CarouselSliceVariation =
  | CarouselSliceDefault
  | CarouselSliceVariation1
  | CarouselSliceVariation2;

/**
 * Carousel Shared Slice
 *
 * - **API ID**: `carousel`
 * - **Description**: Carousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CarouselSlice = prismic.SharedSlice<
  "carousel",
  CarouselSliceVariation
>;

/**
 * Item in *Content → Two columns images → Primary → Images*
 */
export interface ContentSliceTwoColumnsImagesPrimaryImagesItem {
  /**
   * Image field in *Content → Two columns images → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumnsImages.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *Content → Default → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Content field in *Content → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.default.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Content → Two columns → Primary*
 */
export interface ContentSliceTwoColumnsPrimary {
  /**
   * Content left column field in *Content → Two columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumns.primary.content_left_column
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content_left_column: prismic.RichTextField;

  /**
   * Content right column field in *Content → Two columns → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumns.primary.content_right_column
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content_right_column: prismic.RichTextField;
}

/**
 * Two columns variation for Content Slice
 *
 * - **API ID**: `twoColumns`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceTwoColumns = prismic.SharedSliceVariation<
  "twoColumns",
  Simplify<ContentSliceTwoColumnsPrimary>,
  never
>;

/**
 * Primary content in *Content → Two columns image → Primary*
 */
export interface ContentSliceTwoColumnsImagePrimary {
  /**
   * Content field in *Content → Two columns image → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumnsImage.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Image field in *Content → Two columns image → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumnsImage.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image side field in *Content → Two columns image → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content.twoColumnsImage.primary.image_side
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_side: prismic.BooleanField;
}

/**
 * Two columns image variation for Content Slice
 *
 * - **API ID**: `twoColumnsImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceTwoColumnsImage = prismic.SharedSliceVariation<
  "twoColumnsImage",
  Simplify<ContentSliceTwoColumnsImagePrimary>,
  never
>;

/**
 * Primary content in *Content → Quote → Primary*
 */
export interface ContentSliceQuotePrimary {
  /**
   * Content field in *Content → Quote → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.quote.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;
}

/**
 * Quote variation for Content Slice
 *
 * - **API ID**: `quote`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceQuote = prismic.SharedSliceVariation<
  "quote",
  Simplify<ContentSliceQuotePrimary>,
  never
>;

/**
 * Primary content in *Content → Two columns images → Primary*
 */
export interface ContentSliceTwoColumnsImagesPrimary {
  /**
   * Content field in *Content → Two columns images → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumnsImages.primary.content
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  content: prismic.RichTextField;

  /**
   * Images field in *Content → Two columns images → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: content.twoColumnsImages.primary.images[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  images: prismic.GroupField<
    Simplify<ContentSliceTwoColumnsImagesPrimaryImagesItem>
  >;

  /**
   * Images side field in *Content → Two columns images → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: content.twoColumnsImages.primary.images_side
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  images_side: prismic.BooleanField;
}

/**
 * Two columns images variation for Content Slice
 *
 * - **API ID**: `twoColumnsImages`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSliceTwoColumnsImages = prismic.SharedSliceVariation<
  "twoColumnsImages",
  Simplify<ContentSliceTwoColumnsImagesPrimary>,
  never
>;

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation =
  | ContentSliceDefault
  | ContentSliceTwoColumns
  | ContentSliceTwoColumnsImage
  | ContentSliceQuote
  | ContentSliceTwoColumnsImages;

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContentSlice = prismic.SharedSlice<
  "content",
  ContentSliceVariation
>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
  /**
   * Title field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Cta → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.default.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CtaSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Cta → Variation 1 → Primary*
 */
export interface CtaSliceVariation1Primary {
  /**
   * Title field in *Cta → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Cta → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *Cta → Variation 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation1.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *Cta → Variation 1 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation1.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Variation 1 variation for Cta Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<CtaSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Cta → Variation 2 → Primary*
 */
export interface CtaSliceVariation2Primary {
  /**
   * Title field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Input - placeholder field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your email
   * - **API ID Path**: cta.variation2.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Button - Text field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Sign up
   * - **API ID Path**: cta.variation2.primary.btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;

  /**
   * Legals description field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation2.primary.legals_dsc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legals_dsc: prismic.RichTextField;

  /**
   * Image field in *Cta → Variation 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: cta.variation2.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Variation 2 variation for Cta Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<CtaSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation =
  | CtaSliceDefault
  | CtaSliceVariation1
  | CtaSliceVariation2;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaSlice = prismic.SharedSlice<"cta", CtaSliceVariation>;

/**
 * Item in *Faq → Default → Primary → Grp*
 */
export interface FaqSliceDefaultPrimaryGrpItem {
  /**
   * Question field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Faq → Variation 1 → Primary → Grp*
 */
export interface FaqSliceVariation1PrimaryGrpItem {
  /**
   * Question field in *Faq → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Item in *Faq → Variation 2 → Primary → Grp*
 */
export interface FaqSliceVariation2PrimaryGrpItem {
  /**
   * Question field in *Faq → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[].question
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  question: prismic.RichTextField;

  /**
   * Answer field in *Faq → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[].answer
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  answer: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Default → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Button field in *Faq → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Contact
   * - **API ID Path**: faq.default.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;

  /**
   * Grp field in *Faq → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Faq → Variation 1 → Primary*
 */
export interface FaqSliceVariation1Primary {
  /**
   * Title field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceVariation1PrimaryGrpItem>>;

  /**
   * Title - Foot field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.title_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_foot: prismic.RichTextField;

  /**
   * Text - Foot field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.txt_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt_foot: prismic.RichTextField;

  /**
   * Button field in *Faq → Variation 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation1.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Variation 1 variation for Faq Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<FaqSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Faq → Variation 2 → Primary*
 */
export interface FaqSliceVariation2Primary {
  /**
   * Title field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FaqSliceVariation2PrimaryGrpItem>>;

  /**
   * Title - foot field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.title_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_foot: prismic.RichTextField;

  /**
   * Text - Foot field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.txt_foot
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt_foot: prismic.RichTextField;

  /**
   * Button field in *Faq → Variation 2 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.variation2.primary.btn
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btn: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    "Primary" | "Secondary"
  >;
}

/**
 * Variation 2 variation for Faq Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<FaqSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation =
  | FaqSliceDefault
  | FaqSliceVariation1
  | FaqSliceVariation2;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Item in *FeaturedArticles → Default → Primary → Grp*
 */
export interface FeaturedArticlesSliceDefaultPrimaryGrpItem {
  /**
   * Image field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Category field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].category
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  category: prismic.KeyTextField;

  /**
   * Date field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Title field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button - Text field in *FeaturedArticles → Default → Primary → Grp*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[].btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;
}

/**
 * Primary content in *FeaturedArticles → Default → Primary*
 */
export interface FeaturedArticlesSliceDefaultPrimary {
  /**
   * Ontitle field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.ontitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  ontitle: prismic.RichTextField;

  /**
   * Title field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Button - Text field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;

  /**
   * Grp field in *FeaturedArticles → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_articles.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<FeaturedArticlesSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for FeaturedArticles Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedArticlesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedArticlesSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FeaturedArticles*
 */
type FeaturedArticlesSliceVariation = FeaturedArticlesSliceDefault;

/**
 * FeaturedArticles Shared Slice
 *
 * - **API ID**: `featured_articles`
 * - **Description**: FeaturedArticles
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedArticlesSlice = prismic.SharedSlice<
  "featured_articles",
  FeaturedArticlesSliceVariation
>;

/**
 * Default variation for HeroHome Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroHomeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  never
>;

/**
 * Slice variation for *HeroHome*
 */
type HeroHomeSliceVariation = HeroHomeSliceDefault;

/**
 * HeroHome Shared Slice
 *
 * - **API ID**: `hero_home`
 * - **Description**: HeroHome
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroHomeSlice = prismic.SharedSlice<
  "hero_home",
  HeroHomeSliceVariation
>;

/**
 * Primary content in *HeroLanding → Default → Primary*
 */
export interface HeroLandingSliceDefaultPrimary {
  /**
   * Title field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *HeroLanding → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.default.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Default variation for HeroLanding Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroLandingSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 1 → Primary*
 */
export interface HeroLandingSliceVariation1Primary {
  /**
   * Title field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Video field in *HeroLanding → Variation 1 → Primary*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation1.primary.video
   * - **Documentation**: https://prismic.io/docs/fields/embed
   */
  video: prismic.EmbedField;
}

/**
 * Variation 1 variation for HeroLanding Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<HeroLandingSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 2 → Primary*
 */
export interface HeroLandingSliceVariation2Primary {
  /**
   * Title field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Input - placeholder field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter your mail
   * - **API ID Path**: hero_landing.variation2.primary.input_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  input_placeholder: prismic.KeyTextField;

  /**
   * Button - Text field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: S'abonner
   * - **API ID Path**: hero_landing.variation2.primary.btn_txt
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  btn_txt: prismic.KeyTextField;

  /**
   * Image field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Legals description field in *HeroLanding → Variation 2 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation2.primary.legals_dsc
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  legals_dsc: prismic.RichTextField;
}

/**
 * Variation 2 variation for HeroLanding Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<HeroLandingSliceVariation2Primary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 3 → Primary*
 */
export interface HeroLandingSliceVariation3Primary {
  /**
   * Title field in *HeroLanding → Variation 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation3.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 3 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation3.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Variation 3 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation3.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *HeroLanding → Variation 3 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation3.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Variation 3 variation for HeroLanding Slice
 *
 * - **API ID**: `variation3`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation3 = prismic.SharedSliceVariation<
  "variation3",
  Simplify<HeroLandingSliceVariation3Primary>,
  never
>;

/**
 * Primary content in *HeroLanding → Variation 4 → Primary*
 */
export interface HeroLandingSliceVariation4Primary {
  /**
   * Title field in *HeroLanding → Variation 4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation4.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *HeroLanding → Variation 4 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation4.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Buttons field in *HeroLanding → Variation 4 → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation4.primary.btns
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  btns: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *HeroLanding → Variation 4 → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_landing.variation4.primary.img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;
}

/**
 * Variation 4 variation for HeroLanding Slice
 *
 * - **API ID**: `variation4`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSliceVariation4 = prismic.SharedSliceVariation<
  "variation4",
  Simplify<HeroLandingSliceVariation4Primary>,
  never
>;

/**
 * Slice variation for *HeroLanding*
 */
type HeroLandingSliceVariation =
  | HeroLandingSliceDefault
  | HeroLandingSliceVariation1
  | HeroLandingSliceVariation2
  | HeroLandingSliceVariation3
  | HeroLandingSliceVariation4;

/**
 * HeroLanding Shared Slice
 *
 * - **API ID**: `hero_landing`
 * - **Description**: HeroLanding
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroLandingSlice = prismic.SharedSlice<
  "hero_landing",
  HeroLandingSliceVariation
>;

/**
 * Primary content in *Feature → default → Primary*
 */
export interface MediaFeatureSliceDefaultPrimary {
  /**
   * Tagline field in *Feature → default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_feature.default.primary.tagline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  tagline: prismic.KeyTextField;

  /**
   * Title field in *Feature → default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_feature.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Description field in *Feature → default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: media_feature.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Buttons field in *Feature → default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: media_feature.default.primary.buttons
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  buttons: prismic.Repeatable<
    prismic.LinkField<
      string,
      string,
      unknown,
      prismic.FieldState,
      "Primary" | "Secondary"
    >
  >;

  /**
   * Image field in *Feature → default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_feature.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Image side field in *Feature → default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: media_feature.default.primary.image_side
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  image_side: prismic.BooleanField;
}

/**
 * default variation for Feature Slice
 *
 * - **API ID**: `default`
 * - **Description**: Layout with the media (image or video) on the right and textual content (tagline, heading, description, and actions) on the left.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaFeatureSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaFeatureSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Feature*
 */
type MediaFeatureSliceVariation = MediaFeatureSliceDefault;

/**
 * Feature Shared Slice
 *
 * - **API ID**: `media_feature`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaFeatureSlice = prismic.SharedSlice<
  "media_feature",
  MediaFeatureSliceVariation
>;

/**
 * Primary content in *NavigationLinks → Default → Primary*
 */
export interface NavigationLinksSliceDefaultPrimary {
  /**
   * Link field in *NavigationLinks → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.default.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for NavigationLinks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NavigationLinksSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *NavigationLinks → With sublinks → Primary*
 */
export interface NavigationLinksSliceWithSublinksPrimary {
  /**
   * Link field in *NavigationLinks → With sublinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.withSublinks.primary.link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Sublinks field in *NavigationLinks → With sublinks → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation_links.withSublinks.primary.sublinks
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  sublinks: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * With sublinks variation for NavigationLinks Slice
 *
 * - **API ID**: `withSublinks`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSliceWithSublinks = prismic.SharedSliceVariation<
  "withSublinks",
  Simplify<NavigationLinksSliceWithSublinksPrimary>,
  never
>;

/**
 * Slice variation for *NavigationLinks*
 */
type NavigationLinksSliceVariation =
  | NavigationLinksSliceDefault
  | NavigationLinksSliceWithSublinks;

/**
 * NavigationLinks Shared Slice
 *
 * - **API ID**: `navigation_links`
 * - **Description**: NavigationLinks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type NavigationLinksSlice = prismic.SharedSlice<
  "navigation_links",
  NavigationLinksSliceVariation
>;

/**
 * Item in *Testimonials → Default → Primary → Grp*
 */
export interface TestimonialsSliceDefaultPrimaryGrpItem {
  /**
   * Rate field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: testimonials.default.primary.grp[].rate
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  rate: prismic.SelectField<"5" | "4", "filled">;

  /**
   * Quote field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Author field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Default → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Position, Company name
   * - **API ID Path**: testimonials.default.primary.grp[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;
}

/**
 * Item in *Testimonials → Variation 1 → Primary → Grp*
 */
export interface TestimonialsSliceVariation1PrimaryGrpItem {
  /**
   * Rate field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 5
   * - **API ID Path**: testimonials.variation1.primary.grp[].rate
   * - **Documentation**: https://prismic.io/docs/fields/select
   */
  rate: prismic.SelectField<"5" | "4", "filled">;

  /**
   * Quote field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.grp[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.grp[].img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Author field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.grp[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Position, Company name
   * - **API ID Path**: testimonials.variation1.primary.grp[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;

  /**
   * Logo field in *Testimonials → Variation 1 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.grp[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Item in *Testimonials → Variation 2 → Primary → Grp*
 */
export interface TestimonialsSliceVariation2PrimaryGrpItem {
  /**
   * Logo field in *Testimonials → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation2.primary.grp[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Quote field in *Testimonials → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation2.primary.grp[].quote
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  quote: prismic.RichTextField;

  /**
   * Image field in *Testimonials → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation2.primary.grp[].img
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  img: prismic.ImageField<never>;

  /**
   * Author field in *Testimonials → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation2.primary.grp[].author
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  author: prismic.RichTextField;

  /**
   * Company field in *Testimonials → Variation 2 → Primary → Grp*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Position, Company name
   * - **API ID Path**: testimonials.variation2.primary.grp[].company
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  company: prismic.RichTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryGrpItem>>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Testimonials → Variation 1 → Primary*
 */
export interface TestimonialsSliceVariation1Primary {
  /**
   * Title field in *Testimonials → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Text field in *Testimonials → Variation 1 → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.txt
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  txt: prismic.RichTextField;

  /**
   * Grp field in *Testimonials → Variation 1 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation1.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<TestimonialsSliceVariation1PrimaryGrpItem>>;
}

/**
 * Variation 1 variation for Testimonials Slice
 *
 * - **API ID**: `variation1`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceVariation1 = prismic.SharedSliceVariation<
  "variation1",
  Simplify<TestimonialsSliceVariation1Primary>,
  never
>;

/**
 * Primary content in *Testimonials → Variation 2 → Primary*
 */
export interface TestimonialsSliceVariation2Primary {
  /**
   * Grp field in *Testimonials → Variation 2 → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.variation2.primary.grp[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  grp: prismic.GroupField<Simplify<TestimonialsSliceVariation2PrimaryGrpItem>>;
}

/**
 * Variation 2 variation for Testimonials Slice
 *
 * - **API ID**: `variation2`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSliceVariation2 = prismic.SharedSliceVariation<
  "variation2",
  Simplify<TestimonialsSliceVariation2Primary>,
  never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation =
  | TestimonialsSliceDefault
  | TestimonialsSliceVariation1
  | TestimonialsSliceVariation2;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      _404Document,
      _404DocumentData,
      _404DocumentDataSlicesSlice,
      ArticleDocument,
      ArticleDocumentData,
      ArticleDocumentDataSlicesSlice,
      AuthorDocument,
      AuthorDocumentData,
      CategoryDocument,
      CategoryDocumentData,
      ContactDocument,
      ContactDocumentData,
      FooterDocument,
      FooterDocumentData,
      HeaderDocument,
      HeaderDocumentData,
      HeaderDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      LandingDocument,
      LandingDocumentData,
      LandingDocumentDataSlicesSlice,
      RecapDocument,
      RecapDocumentData,
      RecapDocumentDataSlicesSlice,
      RecapDocumentDataKeyProblemItem,
      RecapDocumentDataOpportunityItem,
      RecapDocumentDataGeneratedPageItem,
      RecapDocumentDataStepItem,
      SettingsDocument,
      SettingsDocumentData,
      AllDocumentTypes,
      CarouselSlice,
      CarouselSliceDefaultPrimaryGrpItem,
      CarouselSliceDefaultPrimary,
      CarouselSliceVariation1PrimaryGrpItem,
      CarouselSliceVariation1Primary,
      CarouselSliceVariation2PrimaryGrpItem,
      CarouselSliceVariation2Primary,
      CarouselSliceVariation,
      CarouselSliceDefault,
      CarouselSliceVariation1,
      CarouselSliceVariation2,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceTwoColumnsPrimary,
      ContentSliceTwoColumnsImagePrimary,
      ContentSliceQuotePrimary,
      ContentSliceTwoColumnsImagesPrimaryImagesItem,
      ContentSliceTwoColumnsImagesPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      ContentSliceTwoColumns,
      ContentSliceTwoColumnsImage,
      ContentSliceQuote,
      ContentSliceTwoColumnsImages,
      CtaSlice,
      CtaSliceDefaultPrimary,
      CtaSliceVariation1Primary,
      CtaSliceVariation2Primary,
      CtaSliceVariation,
      CtaSliceDefault,
      CtaSliceVariation1,
      CtaSliceVariation2,
      FaqSlice,
      FaqSliceDefaultPrimaryGrpItem,
      FaqSliceDefaultPrimary,
      FaqSliceVariation1PrimaryGrpItem,
      FaqSliceVariation1Primary,
      FaqSliceVariation2PrimaryGrpItem,
      FaqSliceVariation2Primary,
      FaqSliceVariation,
      FaqSliceDefault,
      FaqSliceVariation1,
      FaqSliceVariation2,
      FeaturedArticlesSlice,
      FeaturedArticlesSliceDefaultPrimaryGrpItem,
      FeaturedArticlesSliceDefaultPrimary,
      FeaturedArticlesSliceVariation,
      FeaturedArticlesSliceDefault,
      HeroHomeSlice,
      HeroHomeSliceVariation,
      HeroHomeSliceDefault,
      HeroLandingSlice,
      HeroLandingSliceDefaultPrimary,
      HeroLandingSliceVariation1Primary,
      HeroLandingSliceVariation2Primary,
      HeroLandingSliceVariation3Primary,
      HeroLandingSliceVariation4Primary,
      HeroLandingSliceVariation,
      HeroLandingSliceDefault,
      HeroLandingSliceVariation1,
      HeroLandingSliceVariation2,
      HeroLandingSliceVariation3,
      HeroLandingSliceVariation4,
      MediaFeatureSlice,
      MediaFeatureSliceDefaultPrimary,
      MediaFeatureSliceVariation,
      MediaFeatureSliceDefault,
      NavigationLinksSlice,
      NavigationLinksSliceDefaultPrimary,
      NavigationLinksSliceWithSublinksPrimary,
      NavigationLinksSliceVariation,
      NavigationLinksSliceDefault,
      NavigationLinksSliceWithSublinks,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimaryGrpItem,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceVariation1PrimaryGrpItem,
      TestimonialsSliceVariation1Primary,
      TestimonialsSliceVariation2PrimaryGrpItem,
      TestimonialsSliceVariation2Primary,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TestimonialsSliceVariation1,
      TestimonialsSliceVariation2,
    };
  }
}
