// Code generated by Prismic. DO NOT EDIT.

import AbmPages from "./AbmPages";
import AbmRoiCalculator from "./AbmRoiCalculator";
import Banner from "./Banner";
import Benefits from "./Benefits";
import Carousel from "./Carousel";
import Contact from "./Contact";
import Content from "./Content";
import Cta from "./Cta";
import EmbedSection from "./EmbedSection";
import Faq from "./Faq";
import FeaturedArticles from "./FeaturedArticles";
import HeroHome from "./HeroHome";
import HeroLanding from "./HeroLanding";
import HeroRecommendation from "./HeroRecommendation";
import Icons from "./Icons";
import Feature from "./Feature";
import NavigationLinks from "./NavigationLinks";
import NextSteps from "./NextSteps";
import Opportunities from "./Opportunities";
import ProductSelection from "./ProductSelection";
import RoiCalculator from "./RoiCalculator";
import SeoPages from "./SeoPages";
import Testimonials from "./Testimonials";
import Understanding from "./Understanding";

export const components = {
	abm_pages: AbmPages,
	abm_roi_calculator: AbmRoiCalculator,
	banner: Banner,
	benefits: Benefits,
	carousel: Carousel,
	contact: Contact,
	content: Content,
	cta: Cta,
	embed_section: EmbedSection,
	faq: Faq,
	featured_articles: FeaturedArticles,
	hero_home: HeroHome,
	hero_landing: HeroLanding,
	hero_recommendation: HeroRecommendation,
	icons: Icons,
	media_feature: Feature,
	navigation_links: NavigationLinks,
	next_steps: NextSteps,
	opportunities: Opportunities,
	product_selection: ProductSelection,
	roi_calculator: RoiCalculator,
	seo_pages: SeoPages,
	testimonials: Testimonials,
	understanding: Understanding
};