// Code generated by Prismic. DO NOT EDIT.

import Banner from "./Banner";
import Carousel from "./Carousel";
import Content from "./Content";
import Cta from "./Cta";
import Faq from "./Faq";
import FeaturedArticles from "./FeaturedArticles";
import HeroHome from "./HeroHome";
import HeroLanding from "./HeroLanding";
import Icons from "./Icons";
import Feature from "./Feature";
import NavigationLinks from "./NavigationLinks";
import ProductSelection from "./ProductSelection";
import Testimonials from "./Testimonials";

export const components = {
	banner: Banner,
	carousel: Carousel,
	content: Content,
	cta: Cta,
	faq: Faq,
	featured_articles: FeaturedArticles,
	hero_home: HeroHome,
	hero_landing: HeroLanding,
	icons: Icons,
	media_feature: Feature,
	navigation_links: NavigationLinks,
	product_selection: ProductSelection,
	testimonials: Testimonials
};